# Generated by Django 4.2.7 on 2026-05-18 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('upload', 'Upload document'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('archivage', 'Archivage'), ('telechargement', 'Téléchargement'), ('creation_utilisateur', 'Création utilisateur'), ('modification_utilisateur', 'Modification utilisateur'), ('suppression_utilisateur', 'Suppression utilisateur'), ('creation_categorie', 'Création catégorie'), ('suppression_categorie', 'Suppression catégorie'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique',
                'ordering': ['-created_at'],
            },
        ),
    ]
