# Generated by Django 4.2.7 on 2026-05-18 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/')),
                ('confidentialite', models.CharField(choices=[('public', 'Public'), ('interne', 'Interne'), ('confidentiel', 'Confidentiel'), ('secret', 'Secret')], default='interne', max_length=20)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé'), ('supprime', 'Supprimé')], default='actif', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archiviste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.categorie')),
                ('tags', models.ManyToManyField(blank=True, to='documents.tag')),
            ],
            options={
                'verbose_name': 'Document',
                'ordering': ['-created_at'],
            },
        ),
    ]
